language: ruby
rvm:
  - "2.3.5"
  - "ruby-head"
gemfile:
  - gemfiles/rails_42.gemfile
env:
  - DB=mysql
  - DB=postgresql
before_install:
  - gem update bundler
before_script:
  - mysql -e 'create database redirector_dummy_test; create database redirector_dummy_development;'
  - psql -c 'create database redirector_dummy_test' -U postgres
  - psql -c 'create database redirector_dummy_development' -U postgres
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - bundle exec rake db:migrate
